workflows:
  build-android:
    name: Build Android (APK + AAB)
    max_build_duration: 30
    environment:
      flutter: stable
      android_signing:
        # 
        keystore_reference: your_keystore_reference
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --debug

      - name: Build AAB
        script: flutter build appbundle --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/app/outputs/bundle/debug/app-debug.aab
