import 'package:flutter/material.dart';
import '../lesson.dart';
import '../lesson_detail_page.dart';
import 'login_page.dart';

class LessonListPage extends StatelessWidget {
  final Map<String, dynamic>? userData;
  const LessonListPage({super.key, this.userData});

  @override
  Widget build(BuildContext context) {
    final lessons = [
      Lesson(
        title: 'Lektion 1: Einführung',
        description: 'Einführung in grundlegendes Deutsch.',
        pdfUrl: 'assets/App/Lektion_1/vt1_eBook_Lektion_1.pdf',
        audioUrls: [
          'App/Lektion_1/Audio_E1_1.mp3',
          'assets/App/Lektion_1/Tab 1_1 - Grußformeln und Befinden - informell.mp3',
          'assets/App/Lektion_1/Tab 1_2 - Grußformeln und Befinden - formell.mp3',
          'assets/App/Lektion_1/Tab 1_3 - Vorstellung - informell.mp3',
          'assets/App/Lektion_1/Tab 1_4 - Vorstellung - formell.mp3',
          'assets/App/Lektion_1/Tab 1_5 - Vorstellung - Alternative.mp3',
          'assets/App/Lektion_1/audio_1_6.mp3',
          'assets/App/Lektion_1/audio_1_7.mp3',
          'assets/App/Lektion_1/Tab 1_8 - Ergänzung zum Dialog.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 2: Begrüßungen',
        description: 'Gängige Begrüßungsphrasen auf Deutsch.',
        pdfUrl: 'assets/App/Lektion_2/vt1_eBook_Lektion_2.pdf',
        audioUrls: [
          'assets/App/Lektion_2/Audio E2_1.mp3',
          'assets/App/Lektion_2/Tab 2_1 - Regionale Begrüßungen - ugs.mp3',
          'assets/App/Lektion_2/Tab 2_2 - Begrüßungen.mp3',
          'assets/App/Lektion_2/Tab 2_3 - Alter und Hobbys - informell.mp3',
          'assets/App/Lektion_2/Tab 2_4 - Alter und Hobbys - formell.mp3',
          'assets/App/Lektion_2/Tab 2_5 - Arbeit - informell.mp3',
          'assets/App/Lektion_2/Tab 2_6 - Arbeit - formell.mp3',
          'assets/App/Lektion_2/Tab 2_7 - Studium - informell und formell.mp3',
          'assets/App/Lektion_2/Tab 2_8 - Studium - Verneinung_arbeiten und studieren.mp3',
          'assets/App/Lektion_2/Tab 2_9 - Berufliche Situation - Alternativen.mp3',
          'assets/App/Lektion_2/Tab 2_10 - Elliptische Gegenfrage - informell und formell.mp3',
          'assets/App/Lektion_2/audio_2_11.mp3',
          'assets/App/Lektion_2/Audio 2_12 - Text - Ich bin Studentin.mp3',
          'assets/App/Lektion_2/Tab 2_13 - Verabschiedungen.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 3: Noch mal, bitte',
        description: 'Text - Noch mal, bitte',
        pdfUrl: 'assets/App/Lektion_3/vt1_eBook_Lektion_3.pdf',
        audioUrls: [
          'assets/App/Lektion_3/Tab 3_1 - Sprachkenntnisse.mp3',
          'assets/App/Lektion_3/Tab 3_2 - Sprachkenntnisse - Variationen.mp3',
          'assets/App/Lektion_3/Tab 3_3 - Verständnisprobleme.mp3',
          'assets/App/Lektion_3/Tab 3_4 - um Wiederholung bitten.mp3',
          'assets/App/Lektion_3/Tab 3_5 - Entschuldigung als Ansprache.mp3',
          'assets/App/Lektion_3/Tab 3_6 - Entschuldigung - Variationen.mp3',
          'assets/App/Lektion_3/Audio 3_7 - Text - Noch mal, bitte.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 4: Kannst du mir kurz helfen',
        description: 'Text - Kannst du mir kurz helfen',
        pdfUrl: 'assets/App/Lektion_4/vt1_eBook_Lektion_4.pdf',
        audioUrls: [
          'assets/App/Lektion_4/Tab 4_1 - ja, nein, vielleicht.mp3',
          'assets/App/Lektion_4/Tab 4_2 - Bestätigung und Verneinung.mp3',
          'assets/App/Lektion_4/Tab 4_3 - danke, bitte, gerne.mp3',
          'assets/App/Lektion_4/Tab 4_4 - danke - Variationen.mp3',
          'assets/App/Lektion_4/Tab 4_5 - bitte und gerne - Variationen.mp3',
          'assets/App/Lektion_4/Tab 4_6 - Fahrkarte und Identifikation.mp3',
          'assets/App/Lektion_4/Tab 4_7 - warten und folgen.mp3',
          'assets/App/Lektion_4/Tab 4_8 - Hilfe anbieten.mp3',
          'assets/App/Lektion_4/Tab 4_9 - um Hilfe bitten.mp3',
          'assets/App/Lektion_4/Tab 4_10 - Orientierung und Verfügbarkeit.mp3',
          'assets/App/Lektion_4/Tab 4_11 - Richtungsangaben.mp3',
          'assets/App/Lektion_4/Tab 4_12 - Ortsangaben.mp3',
          'assets/App/Lektion_4/Tab 4_13 - Preis.mp3',
          'assets/App/Lektion_4/Tab 4_14 - kurze Bestätigung.mp3',
          'assets/App/Lektion_4/Tab 4_15 - kurze Bestätigung ugs.mp3',
          'assets/App/Lektion_4/Audio 4_16 - Text - Kannst du mir kurz helfen.mp3',
          'assets/App/Lektion_4/Audio 4_17 - Text - Wie kann ich Ihnen helfen.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 5: Einen Tisch für zwei Personen bitte',
        description: 'Text - Einen Tisch für zwei Personen bitte',
        pdfUrl: 'assets/App/Lektion_5/vt1_eBook_Lektion_5.pdf',
        audioUrls: [
          'assets/App/Lektion_5/Audio 5_21 - Text - Einen Tisch für zwei Personen bitte.mp3',
          'assets/App/Lektion_5/Audio 5_22 - Text - Was darf ich Ihnen bringen.mp3',
          'assets/App/Lektion_5/Audio 5_23 - Text - Die Rechnung bitte.mp3',
          'assets/App/Lektion_5/Audio W5_1.mp3',
          'assets/App/Lektion_5/Tab 5_1 - Nach einem Tisch fragen.mp3',
          'assets/App/Lektion_5/Tab 5_2 - Tischreservierung.mp3',
          'assets/App/Lektion_5/Tab 5_3 - Bestellung aufnehmen.mp3',
          'assets/App/Lektion_5/Tab 5_4 - um ewas bitten und bestellen.mp3',
          'assets/App/Lektion_5/Tab 5_5 - bestellen-Alternative.mp3',
          'assets/App/Lektion_5/Tab 5_6 - bestellen mit nonverbaler Ergänzung.mp3',
          'assets/App/Lektion_5/Tab 5_7 - weitere Bestellphrasen.mp3',
          'assets/App/Lektion_5/Tab 5_8 - Spezifikationen - vor Ort oder zum Mitnehmen.mp3',
          'assets/App/Lektion_5/Tab 5_9 - Spezifikationen - Getränkezusätze.mp3',
          'assets/App/Lektion_5/Tab 5_10 - Wasserarten.mp3',
          'assets/App/Lektion_5/Tab 5_11 - Alkoholische Getränke.mp3',
          'assets/App/Lektion_5/Tab 5_12 - Bezahlprozess.mp3',
          'assets/App/Lektion_5/Tab 5_13 - Trinkgeld geben.mp3',
          'assets/App/Lektion_5/Tab 5_14 - Quittung.mp3',
          'assets/App/Lektion_5/Tab 5_15 - sich höflich bedanken.mp3',
          'assets/App/Lektion_5/Tab 5_16 - Toilette.mp3',
          'assets/App/Lektion_5/Tab 5_17 - sich entschuldigen.mp3',
          'assets/App/Lektion_5/Tab 5_18 - telefonisch Essen bestellen.mp3',
          'assets/App/Lektion_5/Tab 5_19 - telefonisch Essen bestellen - Adresse angeben.mp3',
          'assets/App/Lektion_5/Tab 5_20 - telefonisch Essen bestellen - Rückfragen und Hinweise.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 6: Wohin möchten Sie fahren',
        description: 'Text - Wohin möchten Sie fahren',
        pdfUrl: 'assets/App/Lektion_6/vt1_eBook_Lektion_6.pdf',
        audioUrls: [
          'assets/App/Lektion_6/Audio 6_13 - Text - Wohin möchten Sie fahren.mp3',
          'assets/App/Lektion_6/Audio 6_14 - Text - Wann kommt der nächste Bus.mp3',
          'assets/App/Lektion_6/Audio W6_1.mp3',
          'assets/App/Lektion_6/Tab 6_1 - Verkehrsmittel - Ich nehme.mp3',
          'assets/App/Lektion_6/Tab 6_2 - Verkehrsmittel - Ich fahre mit.mp3',
          'assets/App/Lektion_6/Tab 6_3 - Verkehrsmittel - zu Fuß und mit dem Flugzeug.mp3',
          'assets/App/Lektion_6/Tab 6_4 - Orientierung und Ticketkauf.mp3',
          'assets/App/Lektion_6/Tab 6_5 - richtiges Verkehrsmittel finden.mp3',
          'assets/App/Lektion_6/Tab 6_6 - Ziel angeben.mp3',
          'assets/App/Lektion_6/Tab 6_7 - um Auskunft bitten.mp3',
          'assets/App/Lektion_6/Tab 6_8 - Verbindung und Umstieg.mp3',
          'assets/App/Lektion_6/Tab 6_9 - Abfahrt und Ankunft.mp3',
          'assets/App/Lektion_6/Tab 6_10 - Verspätung und Ausfall.mp3',
          'assets/App/Lektion_6/Tab 6_11 - Ankunftszeit und Verspätung.mp3',
          'assets/App/Lektion_6/Tab 6_12 - Zimmer buchen.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 7: Sie sind auch nicht von hier, oder',
        description: 'Text - Sie sind auch nicht von hier, oder',
        pdfUrl: 'assets/App/Lektion_7/vt1_eBook_Lektion_7.pdf',
        audioUrls: [
          'assets/App/Lektion_7/Audio 7_10 - Text - Sie sind auch nicht von hier, oder.mp3',
          'assets/App/Lektion_7/Tab 7_1 - Diskursmarker.mp3',
          'assets/App/Lektion_7/Tab 7_2 - Pausenfüller.mp3',
          'assets/App/Lektion_7/Tab 7_3 - Verständnissicherung.mp3',
          'assets/App/Lektion_7/Tab 7_4 - Rückversicherung.mp3',
          'assets/App/Lektion_7/Tab 7_5 - Unwissenheit ausdrücken.mp3',
          'assets/App/Lektion_7/Tab 7_6 - Unwissenheit ausdrücken - Alternativen.mp3',
          'assets/App/Lektion_7/Tab 7_7 - Bestätigungsfragen.mp3',
          'assets/App/Lektion_7/Tab 7_8 - Bestätigung und Zustimmung.mp3',
          'assets/App/Lektion_7/Tab 7_9 - Verneinung und Korrektur.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 8: Wo ist das Fundbüro',
        description: 'Text - Wo ist das Fundbüro',
        pdfUrl: 'assets/App/Lektion_8/vt1_eBook_Lektion_8.pdf',
        audioUrls: [
          'assets/App/Lektion_8/Audio 8_21 - Text - Wo ist das Fundbüro.mp3',
          'assets/App/Lektion_8/Audio 8_22 - Text - Meine Sachen sind weg.mp3',
          'assets/App/Lektion_8/Tab 8_1 - Warnhinweise.mp3',
          'assets/App/Lektion_8/Tab 8_2 - Warnrufe.mp3',
          'assets/App/Lektion_8/Tab 8_3 - Hilfe rufen.mp3',
          'assets/App/Lektion_8/Tab 8_4 - Hilfe anbieten.mp3',
          'assets/App/Lektion_8/Tab 8_5 - auf Hilfsangebote reagieren.mp3',
          'assets/App/Lektion_8/Tab 8_6 - um Auskunft bitten.mp3',
          'assets/App/Lektion_8/Tab 8_7 - um Auskunft bitten - Gibt es hier.mp3',
          'assets/App/Lektion_8/Tab 8_8 - keine Auskunft.mp3',
          'assets/App/Lektion_8/Tab 8_9 - auf keine Auskunft reagieren.mp3',
          'assets/App/Lektion_8/Tab 8_10 - Handy aufladen.mp3',
          'assets/App/Lektion_8/Tab 8_11 - Telefon benutzen.mp3',
          'assets/App/Lektion_8/Tab 8_12 - Akku leer.mp3',
          'assets/App/Lektion_8/Tab 8_13 - Verlust melden.mp3',
          'assets/App/Lektion_8/Tab 8_14 - Verlust melden - Alternative 1.mp3',
          'assets/App/Lektion_8/Tab 8_15 - Verlust melden - Alternative 2.mp3',
          'assets/App/Lektion_8/Tab 8_16 - Diebstahl melden.mp3',
          'assets/App/Lektion_8/Tab 8_17 - Überforderung ausdrücken.mp3',
          'assets/App/Lektion_8/Tab 8_18 - Notruf veranlassen.mp3',
          'assets/App/Lektion_8/Tab 8_19 - Notrufnummern im DACH-Raum.mp3',
          'assets/App/Lektion_8/Tab 8_20 - Euronotrufnummer.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 9: Ihre Adresse bitte',
        description: 'Text - Ihre Adresse bitte',
        pdfUrl: 'assets/App/Lektion_9/vt1_eBook_Lektion_9.pdf',
        audioUrls: [
          'assets/App/Lektion_9/Audio 9_9 - Text - Ihre Adresse bitte.mp3',
          'assets/App/Lektion_9/Tab 9_1 - Wohnadresse und Kontaktdaten.mp3',
          'assets/App/Lektion_9/Tab 9_2 - Wohnadresse und Kontaktdaten - Alternative.mp3',
          'assets/App/Lektion_9/Tab 9_3 - Geburtsdatum.mp3',
          'assets/App/Lektion_9/Tab 9_4 - Geburtstag.mp3',
          'assets/App/Lektion_9/Tab 9_5 - Familienstand.mp3',
          'assets/App/Lektion_9/Tab 9_6 - Kinder.mp3',
          'assets/App/Lektion_9/Tab 9_7 - Geschwister.mp3',
          'assets/App/Lektion_9/Tab 9_8 - Haustiere.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 10: Audio W1',
        description: 'Audio W1',
        pdfUrl: 'assets/App/Lektion_10/vt1_eBook_Lektion_10.pdf',
        audioUrls: [
          'assets/App/Lektion_10/Audio W1.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 11: Wie lange bist du schon hier',
        description: 'Text - Wie lange bist du schon hier',
        pdfUrl: 'assets/App/Lektion_11/vt1_eBook_Lektion_11.pdf',
        audioUrls: [
          'assets/App/Lektion_11/Audio 11_10 - Text - Wie lange bist du schon hier.mp3',
          'assets/App/Lektion_11/Tab 11_1 - Aufenthaltsdauer.mp3',
          'assets/App/Lektion_11/Tab 11_2 - Aufenthaltsdauer - regionale Variante.mp3',
          'assets/App/Lektion_11/Tab 11_3 - Geplanter Aufenthalt.mp3',
          'assets/App/Lektion_11/Tab 11_4 - vergangene Reisen.mp3',
          'assets/App/Lektion_11/Tab 11_5 - besuchte Orte.mp3',
          'assets/App/Lektion_11/Tab 11_6 - Grund des Aufenthalts erfragen.mp3',
          'assets/App/Lektion_11/Tab 11_7 - Grund des Aufenthalts angeben.mp3',
          'assets/App/Lektion_11/Tab 11_8 - Grund des Aufenthalts angeben und erfragen - Alternative.mp3',
          'assets/App/Lektion_11/Tab 11_9 - Grund des Aufenthalts - verkürzt.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 12: Wo waren Sie schon überall',
        description: 'Text - Wo waren Sie schon überall',
        pdfUrl: 'assets/App/Lektion_12/vt1_eBook_Lektion_12.pdf',
        audioUrls: [
          'assets/App/Lektion_12/Audio 12_6 - Text - Wo waren Sie schon überall.mp3',
          'assets/App/Lektion_12/Audio 12_7 - Text - Du bist neu hier, ja.mp3',
          'assets/App/Lektion_12/Tab 12_1 - Meinung zum Aufenthalt.mp3',
          'assets/App/Lektion_12/Tab 12_2 - Gefallen ausdrücken.mp3',
          'assets/App/Lektion_12/Tab 12_3 - über das Deutschlernen sprechen.mp3',
          'assets/App/Lektion_12/Tab 12_4 - über Deutschkenntnisse sprechen.mp3',
          'assets/App/Lektion_12/Tab 12_5 - über besuchte Orte sprechen.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 13: Was machst du gerne in deiner Freizeit',
        description: 'Text - Was machst du gerne in deiner Freizeit',
        pdfUrl: 'assets/App/Lektion_13/vt1_eBook_Lektion_13.pdf',
        audioUrls: [
          'assets/App/Lektion_13/Audio 13_6 - Text - Was machst du gerne in deiner Freizeit.mp3',
          'assets/App/Lektion_13/Tab 13_1 Hobbys nennen - Ich gehe gerne.mp3',
          'assets/App/Lektion_13/Tab 13_2 Hobbys nennen - Ich spiele gerne.mp3',
          'assets/App/Lektion_13/Tab 13_3 Hobbys nennen - Ich mache gerne.mp3',
          'assets/App/Lektion_13/Tab 13_4 Hobbys nennen - Ich verbringe gerne Zeit.mp3',
          'assets/App/Lektion_13/Tab 13_5 nach Hobbys fragen.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 14: Siehst du gerne Filme',
        description: 'Text - Siehst du gerne Filme',
        pdfUrl: 'assets/App/Lektion_14/vt1_eBook_Lektion_14.pdf',
        audioUrls: [
          'assets/App/Lektion_14/Audio 14_14 - Text - Siehst du gerne Filme.mp3',
          'assets/App/Lektion_14/Audio 14_15 - Text - Das Restaurant heißt Roter Hummer.mp3',
          'assets/App/Lektion_14/Tab 14_1 - Vorlieben ausdrücken - Filme und Serien.mp3',
          'assets/App/Lektion_14/Tab 14_2 - Vorlieben ausdrücken - Essen.mp3',
          'assets/App/Lektion_14/Tab 14_3 - Ernährungsweise angeben.mp3',
          'assets/App/Lektion_14/Tab 14_4 - Lieblingsdinge nennen - Bücher.mp3',
          'assets/App/Lektion_14/Tab 14_5 - Lieblingsdinge nennen - Essen.mp3',
          'assets/App/Lektion_14/Tab 14_6 - Meinung ausdrücken mit gefallen.mp3',
          'assets/App/Lektion_14/Tab 14_7 - Meinung ausdrücken mit schmecken.mp3',
          'assets/App/Lektion_14/Tab 14_8 - Gefallen ausdrücken.mp3',
          'assets/App/Lektion_14/Tab 14_9 - Gefallen ausdrücken mit Adjektiven.mp3',
          'assets/App/Lektion_14/Tab 14_10 - Gefallen ausdrücken mit Adjektiven ugs.mp3',
          'assets/App/Lektion_14/Tab 14_11 - Reaktion auf Aussagen und Vorschläge.mp3',
          'assets/App/Lektion_14/Tab 14_12 - Missfallen und Unzufriedenheit ausdrücken.mp3',
          'assets/App/Lektion_14/Tab 14_13 - Graduierung von Meinungen.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 15: Ich koche fast nie',
        description: 'Text - Ich koche fast nie',
        pdfUrl: 'assets/App/Lektion_15/vt1_eBook_Lektion_15.pdf',
        audioUrls: [
          'assets/App/Lektion_15/Audio 15_11 - Text - Ich koche fast nie.mp3',
          'assets/App/Lektion_15/Audio 15_12 - Text - Ein-bis zweimal in der Woche.mp3',
          'assets/App/Lektion_15/Tab 15_1 - Aktionen einleiten.mp3',
          'assets/App/Lektion_15/Tab 15_2 - Antworten zwischen Ja und Nein.mp3',
          'assets/App/Lektion_15/Tab 15_3 - Häufigkeit und Regelmäßigkeit.mp3',
          'assets/App/Lektion_15/Tab 15_4 - Gegenfragen bei Überraschung.mp3',
          'assets/App/Lektion_15/Tab 15_5 - Sätze zur Beruhigung.mp3',
          'assets/App/Lektion_15/Tab 15_6 - Emotionale Bewertung.mp3',
          'assets/App/Lektion_15/Tab 15_7 - Gleichgültigkeit ausdrücken.mp3',
          'assets/App/Lektion_15/Tab 15_8 - Gleichgültigkeit ausdrücken - Alternativen.mp3',
          'assets/App/Lektion_15/Tab 15_9 - Floskeln und Redewendungen.mp3',
          'assets/App/Lektion_15/Tab 15_10 - Aktionen einleiten und Aussagen kommentieren.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 16: Hast du am Sonntag Zeit',
        description: 'Text - Hast du am Sonntag Zeit',
        pdfUrl: 'assets/App/Lektion_16/vt1_eBook_Lektion_16.pdf',
        audioUrls: [
          'assets/App/Lektion_16/Audio 16_10 - Text - Hast du am Sonntag Zeit.mp3',
          'assets/App/Lektion_16/Audio 16_11 - Text - Was machst du am Wochenende.mp3',
          'assets/App/Lektion_16/Tab 16_1 - Aktivitäten vorschlagen - Hast du Lust.mp3',
          'assets/App/Lektion_16/Tab 16_2 - Aktivitäten vorschlagen - Wollen wir.mp3',
          'assets/App/Lektion_16/Tab 16_3 - Aktivitäten vorschlagen - Gehen wir.mp3',
          'assets/App/Lektion_16/Tab 16_4 - Verfügbarkeit und Uhrzeit nennen und erfragen.mp3',
          'assets/App/Lektion_16/Tab 16_5 - Treffpunkt vorschlagen und erfragen.mp3',
          'assets/App/Lektion_16/Tab 16_6 - Treffen zusagen,verschieben und absagen.mp3',
          'assets/App/Lektion_16/Tab 16_7 - über das Wetter sprechen.mp3',
          'assets/App/Lektion_16/Tab 16_8 - Wetterphänomene nennen.mp3',
          'assets/App/Lektion_16/Tab 16_9 - Angaben zur Temperatur.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 17: Wie ist der Name',
        description: 'Text - Wie ist der Name',
        pdfUrl: 'assets/App/Lektion_17/vt1_eBook_Lektion_17.pdf',
        audioUrls: [
          'assets/App/Lektion_17/Audio 17_14 - Text - Wie ist der Name.mp3',
          'assets/App/Lektion_17/Audio 17_15 - Text - Was machst du am Samstag.mp3',
          'assets/App/Lektion_17/Tab 17_1 - Termine vereinbaren.mp3',
          'assets/App/Lektion_17/Tab 17_2 - Terminvorschlag zusagen und ablehnen.mp3',
          'assets/App/Lektion_17/Tab 17_3 - Wochenabschnitte.mp3',
          'assets/App/Lektion_17/Tab 17_4 - Wochentage.mp3',
          'assets/App/Lektion_17/Tab 17_5 - Tageszeiten.mp3',
          'assets/App/Lektion_17/Tab 17_6 - Tageszeiten als Adverbien.mp3',
          'assets/App/Lektion_17/Tab 17_7 - Wochentage als Adverbien.mp3',
          'assets/App/Lektion_17/Tab 17_8 - Uhrzeit erfragen und angeben.mp3',
          'assets/App/Lektion_17/Tab 17_9 - Uhrzeit nennen.mp3',
          'assets/App/Lektion_17/Tab 17_10 - Uhrzeit nennen - 24-Stunden-System.mp3',
          'assets/App/Lektion_17/Tab 17_11 - Uhrzeit mit Tageszeit nennen.mp3',
          'assets/App/Lektion_17/Tab 17_12 - Zeitpunkt erfragen und angeben.mp3',
          'assets/App/Lektion_17/Tab 17_13 - Zeiteinheiten - Sekunde, Minute, Stunde.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 18: Zahnarztpraxis Weiß, Sie sprechen mit Frau Weber',
        description: 'Text - Zahnarztpraxis Weiß, Sie sprechen mit Frau Weber',
        pdfUrl: 'assets/App/Lektion_18/vt1_eBook_Lektion_18.pdf',
        audioUrls: [
          'assets/App/Lektion_18/Audio 18_10 - Text - Zahnarztpraxis Weiß, Sie sprechen mit Frau Weber.mp3',
          'assets/App/Lektion_18/Tab 18_1 - Telefonieren_Begrüßung.mp3',
          'assets/App/Lektion_18/Tab 18_2 - Telefonieren_Begrüßungsformeln.mp3',
          'assets/App/Lektion_18/Tab 18_3 - Telefonieren_Verabschiedung.mp3',
          'assets/App/Lektion_18/Tab 18_4 - Telefonieren_Dank und Abschluss.mp3',
          'assets/App/Lektion_18/Tab 18_5 - Formeller Schriftverkehr - Begrüßung.mp3',
          'assets/App/Lektion_18/Tab 18_6 - Formeller Schriftverkehr - Verabschiedung.mp3',
          'assets/App/Lektion_18/Tab 18_7 - Informeller Schriftverkehr - Begrüßung.mp3',
          'assets/App/Lektion_18/Tab 18_8 - Informeller Schriftverkehr - Verabschiedung.mp3',
          'assets/App/Lektion_18/Tab 18_9 - Abkürzungen in der geschriebenen Sprache.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 19: Ich habe Fieber und Husten',
        description: 'Text - Ich habe Fieber und Husten',
        pdfUrl: 'assets/App/Lektion_19/vt1_eBook_Lektion_19.pdf',
        audioUrls: [
          'assets/App/Lektion_19/Audio 19_11 - Text - Ich habe Fieber und Husten.mp3',
          'assets/App/Lektion_19/Tab 19_1 - Allgemeines Befinden erfragen und ausdrücken.mp3',
          'assets/App/Lektion_19/Tab 19_2 - Allgemeines Befinden - differenzierte Angabe.mp3',
          'assets/App/Lektion_19/Tab 19_3 - Beschwerden erfragen.mp3',
          'assets/App/Lektion_19/Tab 19_4 - Psychisches Befinden ausdrücken.mp3',
          'assets/App/Lektion_19/Tab 19_5 - Physisches Befinden ausdrücken.mp3',
          'assets/App/Lektion_19/Tab 19_6 - Krankheit und Beschwerden nennen.mp3',
          'assets/App/Lektion_19/Tab 19_7 - Beschwerden benennen - Ich habe -schmerzen.mp3',
          'assets/App/Lektion_19/Tab 19_8 - Beschwerden benennen - tut, tun weh.mp3',
          'assets/App/Lektion_19/Tab 19_9 - Krankheiten und Symptome benennen.mp3',
          'assets/App/Lektion_19/Tab 19_10 - Genesungswünsche.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lektion 20: Komm rein',
        description: 'Text - Komm rein',
        pdfUrl: 'assets/App/Lektion_20/vt1_eBook_Lektion_20.pdf',
        audioUrls: [
          'assets/App/Lektion_20/Audio 20_10 - Text - Komm rein.mp3',
          'assets/App/Lektion_20/Audio 20_11 - Text - Wie gefällt Ihnen die Wohnung.mp3',
          'assets/App/Lektion_20/Tab 20_1 - Wohnsituation beschreiben.mp3',
          'assets/App/Lektion_20/Tab 20_2 - vorübergehende Wohnsituation beschreiben.mp3',
          'assets/App/Lektion_20/Tab 20_3 - Wohnsituation beschreiben_Wir-Form.mp3',
          'assets/App/Lektion_20/Tab 20_4 - Details zur Wohnsituation angeben.mp3',
          'assets/App/Lektion_20/Tab 20_5 - Hausarbeiten nennen.mp3',
          'assets/App/Lektion_20/Tab 20_6 - Probleme im Haushalt melden.mp3',
          'assets/App/Lektion_20/Tab 20_7 - Besuch empfangen.mp3',
          'assets/App/Lektion_20/Tab 20_8 - Besuch bewirten.mp3',
          'assets/App/Lektion_20/Tab 20_9 - Wohnungsführung.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Anhang: Referenzlisten',
        description: 'Anhang - Referenzlisten.',
        pdfUrl: 'assets/App/Anhang_Referenzlisten/vt1_eBook_Anhang.pdf',
        audioUrls: [
          'assets/App/Anhang_Referenzlisten/Ref_1 - Alphabet und Buchstabiertafel.mp3',
          'assets/App/Anhang_Referenzlisten/Ref_2 - Ländernamen.mp3',
          'assets/App/Anhang_Referenzlisten/Ref_3 - Städtenamen.mp3',
          'assets/App/Anhang_Referenzlisten/Ref_4 - Berufsbezeichnungen.mp3',
          'assets/App/Anhang_Referenzlisten/Ref_5 - Kardinalzahlen.mp3',
          'assets/App/Anhang_Referenzlisten/Ref_6 - Ordinalzahlen.mp3',
          'assets/App/Anhang_Referenzlisten/Ref_7 - Monatsnamen.mp3',
          'assets/App/Anhang_Referenzlisten/Ref_8 - Farben.mp3',
        ],
        videoUrl: '',
      ),
      Lesson(
        title: 'Lösungen',
        description: 'Lösungen zum eBook.',
        pdfUrl: 'assets/App/Losungen/vt1_eBook_Losungen.pdf',
        audioUrls: [],
        videoUrl: '',
      ),
      Lesson(
        title: 'Titelei und IHV',
        description: 'Titelei und IHV.',
        pdfUrl: 'assets/App/Titelei und IHV/vt1_eBook_Titelei_IHV.pdf',
        audioUrls: [],
        videoUrl: '',
      ),
      Lesson(
        title: 'Wiederholung und Sprechtraining',
        description: 'Wiederholung und Sprechtraining.',
        pdfUrl: 'assets/App/Wiederholung_und_Sprechtraining/vt1_eBook_Wiederholung_und_Sprechtraining.pdf',
        audioUrls: [
          'assets/App/Wiederholung_und_Sprechtraining/Audio ST01.mp3',
          'assets/App/Wiederholung_und_Sprechtraining/Audio ST02.mp3',
          'assets/App/Wiederholung_und_Sprechtraining/Audio W2.mp3',
        ],
        videoUrl: '',
      ),
    ];

    return Scaffold(
      appBar: AppBar(
        title: const Text('Lektionsliste'),
        actions: [
          PopupMenuButton<String>(
            icon: const Icon(Icons.account_circle),
            onSelected: (value) async {
              if (value == 'info') {
                showDialog(
                  context: context,
                  builder: (context) => AlertDialog(
                    title: const Text('Benutzerinfo'),
                    content: Text(userData != null
                        ? 'Name: ${userData!['full_name'] ?? ''}\nEmail: ${userData!['email'] ?? ''}\nTelefon: ${userData!['phone'] ?? ''}'
                        : 'Keine Benutzerdaten'),
                    actions: [
                      TextButton(
                        onPressed: () => Navigator.of(context).pop(),
                        child: const Text('Schließen'),
                      ),
                    ],
                  ),
                );
              } else if (value == 'logout') {
                
                // await Supabase.instance.client.auth.signOut();
                Navigator.of(context).pushReplacement(
                  MaterialPageRoute(builder: (_) => const LoginPage()),
                );
              }
            },
            itemBuilder: (context) => [
              const PopupMenuItem(value: 'info', child: Text('Benutzerinfo')),
              const PopupMenuItem(value: 'logout', child: Text('Abmelden')),
            ],
          ),
        ],
      ),
      body: ListView.builder(
        itemCount: lessons.length,
        itemBuilder: (context, index) {
          final lesson = lessons[index];
          return ListTile(
            title: Text(lesson.title),
            subtitle: Text(lesson.description),
            trailing: const Icon(Icons.arrow_forward_ios),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => LessonDetailPage(lesson: lesson),
                ),
              );
            },
          );
        },
      ),
    );
  }
} 